version: "3.8"

services:
  db:
    image: mariadb:10.3
    container_name: mariadb_cbla
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: secreta
      MYSQL_DATABASE: CBLA
      MYSQL_USER: root
      MYSQL_PASSWORD: secreta
    ports:
      - "3309:3306"
    volumes:
      - dbdata:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin_cbla
    restart: always
    environment:
      PMA_HOST: db
      PMA_PORT: 3306
      PMA_ARBITRARY: 1
      MYSQL_ROOT_PASSWORD: secreta
    ports:
      - "3302:80"
    depends_on:
      - db

volumes:
  dbdata:
